version: 2.1

executors:
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          executor: jdk11
          filters:
            branches:
              ignore:
                - master
  maven_deploy:
    jobs:
      - maven/test:
          executor: jdk11
          command: '-s .circleci/settings.xml deploy'
          filters:
            branches:
              only:
                - master